<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-SHNC452" failures="1" tests="5" name="failedTestCase.TestClass" time="0.029" errors="0" timestamp="2025-01-15T16:19:34 IST" skipped="3">
  <testcase classname="failedTestCase.TestClass" name="user1" time="0.003">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at failedTestCase.TestClass.user1(TestClass.java:15)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- user1 -->
  <system-out/>
  <testcase classname="failedTestCase.TestClass" name="user1" time="0.003">
    <skipped/>
  </testcase> <!-- user1 -->
  <system-out/>
  <testcase classname="failedTestCase.TestClass" name="user1" time="0.001">
    <skipped/>
  </testcase> <!-- user1 -->
  <system-out/>
  <testcase classname="failedTestCase.TestClass" name="login" time="0.021"/>
  <system-out/>
  <testcase classname="failedTestCase.TestClass" name="user1" time="0.001">
    <skipped/>
  </testcase> <!-- user1 -->
  <system-out/>
</testsuite> <!-- failedTestCase.TestClass -->
